# Rain Alert
import requests
import os
from twilio.rest import Client
# from twilio.http.http_client import TwilioHttpClient # Just to run it every day 7am using pythonanywhere

API_KEY = "2e9aae20524dadde20bc03e8d2ff83ba" # os.environ.get("OWM_API_KEY") # Gets api key from the environment

MY_LATITUDE = 37.566536
MY_LONGITUDE = 126.977966

ACCOUNT_SID = "My id"
AUTH_TOKEN = "My authentication token" # os.environ.get("AUTH_TOKEN") # Gets auth token from the environment

parameters = {
    "lat": MY_LATITUDE,
    "lon": MY_LONGITUDE,
    "cnt": 4,
    "appid": API_KEY
}

response = requests.get("https://api.openweathermap.org/data/2.5/forecast?", params=parameters)
response.raise_for_status()
weather_data = response.json()
# print(weather_data["list"])

will_rain = False

for three_hour_period in weather_data["list"]:
    code = three_hour_period["weather"][0]["id"]
    if int(code) < 700:
        will_rain = True
if will_rain:
    # proxy_client = TwilioHttpClient() # Just to run it every day 7am using pythonanywhere
    # proxy_client.session.proxies = {'https': os.environ['https_proxy']} # Just to run it every day 7am using pythonanywhere
    client = Client(ACCOUNT_SID, AUTH_TOKEN)
    # client = Client(ACCOUNT_SID, AUTH_TOKEN, http_client=proxy_client) # Just to run it every day 7am using pythonanywhere
    message = client.messages.create(
        body="It is going to rain today. Remember to bring an umbrella",
        from_="Trial Number", # Phone number generated by twilio
        to="Your verified number" # My actual phone number
    )