import os
from twilio.rest import Client
from dotenv import load_dotenv

load_dotenv()

class NotificationManager:
    #This class is responsible for sending notifications with the deal flight details.
    def __init__(self, price, departure_code, arrival_code, outbound_date, inbound_date):
        self.price = price
        self.departure_code = departure_code
        self.arrival_code = arrival_code
        self.outbound_date = outbound_date
        self.inbound_date =  inbound_date
        self.twilio_id = os.environ["TWILIO_SID"]
        self.twilio_auth_token = os.environ["TWILIO_AUTH_TOKEN"]
        self.twilio_virtual_number = os.environ["TWILIO_VIRTUAL_NUMBER"]
        self.twilio_verified_number = os.environ["TWILIO_VERIFIED_NUMBER"]

    def send_message(self):
        # client = Client(self.twilio_id, self.twilio_auth_token)
        # message = client.messages.create(
        #     body=f"Low price alert! Only {self.price}KRW to fly from {self.departure_code} "
        #          f"to {self.arrival_code}, on {self.outbound_date} until {self.inbound_date}",
        #     from_=self.twilio_virtual_number,  # Phone number generated by twilio
        #     to=self.twilio_verified_number  # My actual phone number
        # )
        print("message is sent")
